### ISSUE TITLE
If we're looking for talent with an ID who already has a sponsor, he throws in 500

### ISSUE THREAD

**Issue by BodyaAnashkin** [Vladyslav-Team/quality-assurance-engineer#23]
- Log in to your sponsor account
 - Return the list of talents and sponsors
 - Find a talent by sponsor id

![Image](https://github.com/Vladyslav-Team/quality-assurance-engineer/assets/95252447/b844b823-16a1-4b56-b154-e20bb68e87ff)

![Image](https://github.com/Vladyslav-Team/quality-assurance-engineer/assets/95252447/838d366b-58b0-4244-9c0d-6a8282164661)

**Comment by PanfiDen** [comment]
The following message will now be sent: "User with such credentials is not found"

[Qa_#23 Pull Request#199](https://github.com/Vladyslav-Team/backend/pull/199)
