### ISSUE TITLE
There is some Skills that can`t be added to the Proof.

### ISSUE THREAD

**Issue by DariaHontar** [Vladyslav-Team/quality-assurance-engineer#30]
**Steps to reproduce:**
1. Log in as an Talent.
2. Add new Proof.
3. Add skills to the proof: Python, Scala, Kotlin and Verylog.

**Ecxepted result:**
Every choosen Skill was added to the Proof.

**Actual result:**
There is 2 identical Skill. No one of them can`t be added.

![Image](https://github.com/Vladyslav-Team/quality-assurance-engineer/assets/116639104/eb84c3a7-74bd-40ca-98e2-b04a023b3d60)

https://github.com/Vladyslav-Team/quality-assurance-engineer/assets/116639104/364e7cbe-b4ef-45eb-8fb3-989a1839a298

**Comment by PanfiDen** [comment]
fixed in [4.2.1 ft Display all skills in profile with gray color if they are not verified #159](https://github.com/Vladyslav-Team/backend/issues/159)
